#!/usr/bin/env sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run ESLint on staged files
npx eslint --ignore-path .gitignore --ignore-pattern **/node_modules/** --cache --quiet --max-warnings 0 --ext .js .

# Run tests
npm test

